import 'dart:typed_data';

// ============================================================
// CODEC — XOR string deobfuscator
// ============================================================
// PURPOSE: All sensitive strings (API endpoint, AppsFlyer key,
// Firebase project ID) are stored as XOR-encoded byte arrays
// instead of plain string literals.
//
// HOW IT WORKS:
//   1. A seed phrase (project-specific, 6-12 ASCII chars) drives
//      an LCG (linear congruential generator) to produce a 16-byte key.
//   2. d(byteArray) XORs each byte against key[i % 16] and returns
//      the decoded UTF-8 string.
//   3. Use tool/encode_keys.dart to generate new byte arrays from
//      your plaintext values.
//
// TODO: Change the seed bytes below for each new project.
//       The seed must be unique per project — it changes the
//       entire key, making this binary distinct from others.
//       Pick any short ASCII phrase meaningful to the project
//       (e.g. game name, slug, internal codename).
//
// EXAMPLE seed bytes for "chicktrip" (hex):
//   0x63, 0x68, 0x69, 0x63, 0x6B, 0x74, 0x72, 0x69, 0x70
//
// TO CHANGE:
//   1. Pick a new ASCII phrase
//   2. Replace the bytes in _deriveKey() `parts` const below
//   3. Run tool/encode_keys.dart to re-encode all secrets
//   4. Paste new byte arrays into analytics_info.dart and net_info.dart
// ============================================================

Uint8List _deriveKey() {
  // TODO: Replace these bytes with the seed for YOUR project.
  // Convert each character of your seed phrase to its ASCII/Unicode
  // decimal value. Example: 'myapp' → [109, 121, 97, 112, 112]
  const parts = <int>[
    // TODO: seed bytes here, e.g.: 0x6D, 0x79, 0x61, 0x70, 0x70
  ];

  if (parts.isEmpty) {
    // Fallback zero-key — REPLACE SEED BEFORE RELEASE
    return Uint8List(16);
  }

  final seed = parts.fold<int>(0, (a, b) => (a * 31 + b) & 0xFFFFFFFF);
  final key = Uint8List(16);
  var v = seed;
  for (var i = 0; i < key.length; i++) {
    v = (v * 1103515245 + 12345) & 0x7FFFFFFF;
    key[i] = v & 0xFF;
  }
  return key;
}

final _xk = _deriveKey();

/// Decodes an XOR-encoded byte list back to a plain string.
/// Pass encoded byte arrays generated by tool/encode_keys.dart.
String d(List<int> data) {
  final out = Uint8List(data.length);
  for (var i = 0; i < data.length; i++) {
    out[i] = data[i] ^ _xk[i % _xk.length];
  }
  return String.fromCharCodes(out);
}
